CREATE DATABASE IF NOT EXISTS RESTAURANTE;

CREATE USER IF NOT EXISTS 'RESTAURANTE'@'localhost' IDENTIFIED BY 'userUSER2';
GRANT ALL PRIVILEGES ON RESTAURANTE.* TO 'RESTAURANTE'@'localhost';

USE RESTAURANTE;

CREATE TABLE CLIENTE(
    CORREO_CLIENTE VARCHAR(50) PRIMARY KEY,
    CONTRASENA VARCHAR(30) NOT NULL
);

CREATE TABLE RESERVA(
    FECHA DATE,
    HORA TIME,
    MESA INT,
    DESCRIPCION VARCHAR(250),
    CORREO_CLIENTE VARCHAR(50),
    PRIMARY KEY (FECHA, HORA, MESA),
    FOREIGN KEY (CORREO_CLIENTE) REFERENCES CLIENTE(CORREO_CLIENTE)
);

CREATE TABLE EMPLEADO(
    USUARIO_EMPLEADO VARCHAR(50) PRIMARY KEY,
    CONTRASENA VARCHAR(30) NOT NULL
);


